# Generated by Django 6.0.1 on 2026-01-29 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('resultado', models.TextField()),
                ('inicio', models.DateTimeField(auto_now_add=True)),
                ('fin', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
