# Generated by Django 6.0.2 on 2026-02-03 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('comandos', models.CharField(max_length=400)),
                ('resultado', models.TextField()),
                ('inicio', models.DateTimeField(auto_now_add=True)),
                ('fin', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
