# Generated by Django 6.0.1 on 2026-01-29 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('script_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='nombre',
            field=models.CharField(max_length=300),
        ),
    ]
