# Generated by Django 6.0.1 on 2026-01-30 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('script_manager', '0002_alter_script_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='comandos',
            field=models.CharField(default='hoal', max_length=400),
            preserve_default=False,
        ),
    ]
